### ISSUE TITLE
Mojolicious 9.0

### ISSUE THREAD

**Issue by kraih** [simbabque/Mojo-Log-Colored#4]
Log formatting has changed a bit with the 9.0 release. Instead of newlines we now just join multiple log messages with a whitespace character (for better contextual logging). https://github.com/mojolicious/mojo/commit/3bc8649ae02325d67c3db0385fdcb7312eeffeee

**Comment by simbabque** [comment]
Thanks for letting me know!

What's the way of handling backwards compatibility here? Would I change my code to adapt the 9.0 way, and would that break backwards compatibility? Or should I check for the version and allow both?

**Comment by kraih** [comment]
I'm afraid there is no backwards compatibility, it's a breaking change in 9.0.
